DROP TABLE IF EXISTS `HOT_WORDS`;

CREATE TABLE `HOT_WORDS` (
  `WORD` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `HOT_STOPWORDS`;

CREATE TABLE `HOT_STOPWORDS` (
  `STOPWORD` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
